import{a as v,S,i}from"./assets/vendor-BNibzuFn.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const R="https://pixabay.com/api/",q="52828842-5c1784e92de7248ba7b84eab7",f=15;async function m(n,o=1){const t={key:q,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:f};return(await v.get(R,{params:t})).data}const y=document.querySelector(".gallery"),g=document.querySelector(".loader"),L=document.querySelector(".load-more"),E=new S(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"});function b(n){const o=n.map(t=>`
      <li class="gallery-item">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" />
        </a>
        <div class="stats">
          <p> ${t.likes}</p>
          <p> ${t.views}</p>
          <p> ${t.comments}</p>
          <p> ${t.downloads}</p>
        </div>
      </li>`).join("");y.insertAdjacentHTML("beforeend",o),E.refresh()}function P(){y.innerHTML=""}function w(){g.classList.remove("hidden")}function l(){g.classList.add("hidden")}function B(){L.classList.remove("hidden")}function u(){L.classList.add("hidden")}const h=document.querySelector(".form"),M=h.elements["search-text"],$=document.querySelector(".load-more");let p="",a=1,c=0;h.addEventListener("submit",O);$.addEventListener("click",x);async function O(n){n.preventDefault();const o=M.value.trim();if(!o){i.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}p=o,a=1,c=0,P(),u(),w();try{const t=await m(p,a);l();const{hits:s,totalHits:e}=t;if(c=e,!s.length){i.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(s),a*f<c?B():(u(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{l(),i.error({title:"Error",message:"Something went wrong while fetching images.",position:"topRight"})}finally{h.reset()}}async function x(){a+=1,w();try{const n=await m(p,a);l();const{hits:o}=n;b(o);const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),a*f>=c&&(u(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{l(),i.error({title:"Error",message:"Unable to load more images.",position:"topRight"})}}
//# sourceMappingURL=index.js.map
